# Generated by Django 3.2.8 on 2021-10-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_details',
            name='status',
            field=models.CharField(choices=[('approved', 'approved'), ('pending', 'pending')], default='pending', max_length=100),
        ),
    ]
